#! /usr/bin/env python3
# coding:utf-8

import random



adjective = [
  "ace",
  "adorable",
  "amazing",
  "astonishing",
  "astounding",
  "awe-inspiring",
  "awesome",
  "baboosh",
  "badass",
  "beautiful",
  "bedazzling",
  "best",
  "bravissimo",
  "breathtaking",
  "brightest",
  "brilliant",
  "charming",
  "clever",
  "chic",
  "classy",
  "clever",
  "cool",
  "crackin'",
  "cute",
  "dandy",
  "dazzling",
  "delicate",
  "delicious",
  "delightful",
  "distinctive",
  "divine",
  "dope",
  "elegant",
  "epic",
  "excellent",
  "exclusive",
  "exceptional",
  "exciting",
  "exquisite",
  "extraordinary",
  "fabulous",
  "fancy",
  "fantastic",
  "fantabulosus",
  "fantabulous",
  "fascinating",
  "fine",
  "finest",
  "first-class",
  "first-rate",
  "flawless",
  "formidable",
  "funkadelic",
  "geometric",
  "glorious",
  "gnarly",
  "good",
  "good-looking",
  "gorgeous",
  "grand",
  "great",
  "groovy",
  "groundbreaking",
  "hip",
  "hot",
  "hunky-dory",
  "impeccable",
  "impressive",
  "incredible",
  "irresistible",
  "just wow",
  "kickass",
  "kryptonian",
  "laudable",
  "legendary",
  "lovely",
  "luminous",
  "magnificent",
  "magnifique",
  "majestic",
  "marvelous",
  "mathematical",
  "metal",
  "mind-blowing",
  "miraculous",
  "nice",
  "neat",
  "nice",
  "outstanding",
  "particular",
  "peachy",
  "peculiar",
  "perfect",
  "phenomenal",
  "pioneering",
  "polished",
  "posh",
  "praiseworthy",
  "premium",
  "priceless",
  "prime",
  "primo",
  "proper",
  "rad",
  "radical",
  "remarkable",
  "riveting",
  "rockandroll",
  "rockin",
  "sensational",
  "sharp",
  "shining",
  "slick",
  "smart",
  "smashing",
  "solid",
  "special",
  "spectacular",
  "spiffing",
  "splendery-doodley",
  "splendid",
  "splendiferous",
  "stellar",
  "striking",
  "stonking",
  "stunning",
  "stupefying",
  "stupendous",
  "stylish",
  "sublime",
  "supah",
  "super",
  "super-duper",
  "super-excellent",
  "super-good",
  "superb",
  "superior",
  "supreme",
  "sweet",
  "sweetest",
  "swell",
  "terrific",
  "tiptop",
  "top-notch",
  "transcendent",
  "tremendous",
  "tubular",
  "ultimate",
  "unique",
  "unbelievable",
  "unreal",
  "well-made",
  "wicked",
  "wise",
  "wonderful",
  "wondrous",
  "world-class"
]


# adverb_manner = [
#   "beautifully",
#   "bellissimo",
#   "bigly",
#   "bravely",
#   "brightly",
#   "calmly",
#   "carefully",
#   "cautiously",
#   "cheerfully",
#   "clearly",
#   "correctly",
#   "courageously",
#   "daringly",
#   "deliberately",
#   "doubtfully",
#   "eagerly",
#   "easily",
#   "effectively",
#   "elegantly",
#   "enormously",
#   "enthusiastically",
#   "faithfully",
#   "fast",
#   "fondly",
#   "fortunately",
#   "frankly",
#   "frantically",
#   "generously",
#   "gently",
#   "gladly",
#   "gracefully",
#   "happily",
#   "healthily",
#   "honestly",
#   "joyously",
#   "justly",
#   "kindly",
#   "neatly",
#   "openly",
#   "patiently",
#   "perfectly",
#   "politely",
#   "powerfully",
#   "quickly",
#   "quietly",
#   "rapidly",
#   "really",
#   "regularly",
#   "repeatedly",
#   "rightfully",
#   "seriously",
#   "sharply",
#   "smoothly",
#   "speedily",
#   "successfully",
#   "swiftly",
#   "tenderly",
#   "thoughtfully",
#   "truthfully",
#   "trustfully",
#   "warmly",
#   "well",
#   "wisely"
# ]


# adverb = adverb_manner

# exclamation =[  
#   "ah",
#   "aha",
#   "ahh",
#   "ahhh",
#   "aw",
#   "aww",
#   "awww",
#   "amazeballs",
#   "aye",
#   "booyeah",
#   "cowabunga",
#   "gee",
#   "ha",
#   "hah",
#   "hmm",
#   "ho-ho",
#   "huh",
#   "heh",
#   "hooah",
#   "hooray",
#   "hurrah",
#   "hurray",
#   "huzzah",
#   "mhm",
#   "mm",
#   "mmh",
#   "mmhm",
#   "mmm",
#   "oh",
#   "ole",
#   "ooh",
#   "uh-hu",
#   "wee",
#   "whee",
#   "whoa",
#   "wow",
#   "wowie",
#   "yahoo",
#   "yay",
#   "yeah",
#   "yeahyah",
#   "yee-haw",
#   "yikes",
#   "yippie",
#   "yow",
#   "yowza"
# ]



# smiley =[
#   ":)",
#   ":D",
#   ":-D",
#   ";)",
#   "(-:",
#   "B-)"
# ]
  



# created = [
#   "assembled",
#   "brewed",
#   "built",
#   "created",
#   "composed",
#   "constructed",
#   "designed",
#   "devised",
#   "done",
#   "forged",
#   "formed",
#   "initiated",
#   "invented",
#   "made",
#   "organized",
#   "planned",
#   "prepared",
#   "set up",
#   "thrown together"
# ]

# creating = [
#   "assembling",
#   "brewing",
#   "building",
#   "creating",
#   "composing",
#   "constructing",
#   "designing",
#   "devising",
#   "forging",
#   "forming",
#   "initiating",
#   "inventing",
#   "making",
#   "organizing",
#   "planning",
#   "preparin",
#   "setting up"
# ]


# def praise_parts(
#     adjective = adjective,
#     adverb = adverb,
#     adverb_manner = adverb_manner,
#     created = created,
#     creating = creating,
#     exclamation = exclamation,
#     smiley = smiley
# ):
#     print

def praise():
    print("你他吗真的{adjective1}".format(adjective1 = random.sample(adjective,1)[0]),"!")

# R-part
# praise <- function(template = "You are ${adjective}!") {
#   while (is_template(template)) {
#     template <- replace_one_template(template)
#   }
#   template
# }


if __name__ == "__main__":
    praise()